name: Publish Docker Image
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web


  push_to_registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}